// <auto-generated />
namespace EfCodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class V2u3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V2u3));
        
        string IMigrationMetadata.Id
        {
            get { return "202012101345436_V2u3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
