// <auto-generated />
namespace EfCodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class V12 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V12));
        
        string IMigrationMetadata.Id
        {
            get { return "202012101412487_V12"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
